-- AlterTable
ALTER TABLE "Effect" ALTER COLUMN "scalarScaleX" DROP DEFAULT,
ALTER COLUMN "scalarScaleX" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "scalarScaleY" DROP DEFAULT,
ALTER COLUMN "scalarScaleY" SET DATA TYPE DOUBLE PRECISION;
