
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserPage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model UserPage
 * 
 */
export type UserPageModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPagePayload>

export type AggregateUserPage = {
  _count: UserPageCountAggregateOutputType | null
  _min: UserPageMinAggregateOutputType | null
  _max: UserPageMaxAggregateOutputType | null
}

export type UserPageMinAggregateOutputType = {
  id: string | null
  pageId: string | null
  uid: string | null
  rank: string | null
  isPinned: boolean | null
}

export type UserPageMaxAggregateOutputType = {
  id: string | null
  pageId: string | null
  uid: string | null
  rank: string | null
  isPinned: boolean | null
}

export type UserPageCountAggregateOutputType = {
  id: number
  pageId: number
  uid: number
  rank: number
  isPinned: number
  _all: number
}


export type UserPageMinAggregateInputType = {
  id?: true
  pageId?: true
  uid?: true
  rank?: true
  isPinned?: true
}

export type UserPageMaxAggregateInputType = {
  id?: true
  pageId?: true
  uid?: true
  rank?: true
  isPinned?: true
}

export type UserPageCountAggregateInputType = {
  id?: true
  pageId?: true
  uid?: true
  rank?: true
  isPinned?: true
  _all?: true
}

export type UserPageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserPage to aggregate.
   */
  where?: Prisma.UserPageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPages to fetch.
   */
  orderBy?: Prisma.UserPageOrderByWithRelationInput | Prisma.UserPageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserPageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserPages
  **/
  _count?: true | UserPageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserPageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserPageMaxAggregateInputType
}

export type GetUserPageAggregateType<T extends UserPageAggregateArgs> = {
      [P in keyof T & keyof AggregateUserPage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserPage[P]>
    : Prisma.GetScalarType<T[P], AggregateUserPage[P]>
}




export type UserPageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserPageWhereInput
  orderBy?: Prisma.UserPageOrderByWithAggregationInput | Prisma.UserPageOrderByWithAggregationInput[]
  by: Prisma.UserPageScalarFieldEnum[] | Prisma.UserPageScalarFieldEnum
  having?: Prisma.UserPageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserPageCountAggregateInputType | true
  _min?: UserPageMinAggregateInputType
  _max?: UserPageMaxAggregateInputType
}

export type UserPageGroupByOutputType = {
  id: string
  pageId: string
  uid: string
  rank: string
  isPinned: boolean
  _count: UserPageCountAggregateOutputType | null
  _min: UserPageMinAggregateOutputType | null
  _max: UserPageMaxAggregateOutputType | null
}

type GetUserPageGroupByPayload<T extends UserPageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserPageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserPageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserPageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserPageGroupByOutputType[P]>
      }
    >
  >



export type UserPageWhereInput = {
  AND?: Prisma.UserPageWhereInput | Prisma.UserPageWhereInput[]
  OR?: Prisma.UserPageWhereInput[]
  NOT?: Prisma.UserPageWhereInput | Prisma.UserPageWhereInput[]
  id?: Prisma.UuidFilter<"UserPage"> | string
  pageId?: Prisma.UuidFilter<"UserPage"> | string
  uid?: Prisma.StringFilter<"UserPage"> | string
  rank?: Prisma.StringFilter<"UserPage"> | string
  isPinned?: Prisma.BoolFilter<"UserPage"> | boolean
  page?: Prisma.XOR<Prisma.PageScalarRelationFilter, Prisma.PageWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserPageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  uid?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  isPinned?: Prisma.SortOrder
  page?: Prisma.PageOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserPageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  rank_uid?: Prisma.UserPageRankUidCompoundUniqueInput
  AND?: Prisma.UserPageWhereInput | Prisma.UserPageWhereInput[]
  OR?: Prisma.UserPageWhereInput[]
  NOT?: Prisma.UserPageWhereInput | Prisma.UserPageWhereInput[]
  pageId?: Prisma.UuidFilter<"UserPage"> | string
  uid?: Prisma.StringFilter<"UserPage"> | string
  rank?: Prisma.StringFilter<"UserPage"> | string
  isPinned?: Prisma.BoolFilter<"UserPage"> | boolean
  page?: Prisma.XOR<Prisma.PageScalarRelationFilter, Prisma.PageWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "rank_uid">

export type UserPageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  uid?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  isPinned?: Prisma.SortOrder
  _count?: Prisma.UserPageCountOrderByAggregateInput
  _max?: Prisma.UserPageMaxOrderByAggregateInput
  _min?: Prisma.UserPageMinOrderByAggregateInput
}

export type UserPageScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserPageScalarWhereWithAggregatesInput | Prisma.UserPageScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserPageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserPageScalarWhereWithAggregatesInput | Prisma.UserPageScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"UserPage"> | string
  pageId?: Prisma.UuidWithAggregatesFilter<"UserPage"> | string
  uid?: Prisma.StringWithAggregatesFilter<"UserPage"> | string
  rank?: Prisma.StringWithAggregatesFilter<"UserPage"> | string
  isPinned?: Prisma.BoolWithAggregatesFilter<"UserPage"> | boolean
}

export type UserPageCreateInput = {
  id?: string
  rank: string
  isPinned: boolean
  page: Prisma.PageCreateNestedOneWithoutUserPagesInput
  user: Prisma.UserCreateNestedOneWithoutUserPagesInput
}

export type UserPageUncheckedCreateInput = {
  id?: string
  pageId: string
  uid: string
  rank: string
  isPinned: boolean
}

export type UserPageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  page?: Prisma.PageUpdateOneRequiredWithoutUserPagesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutUserPagesNestedInput
}

export type UserPageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  uid?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserPageCreateManyInput = {
  id?: string
  pageId: string
  uid: string
  rank: string
  isPinned: boolean
}

export type UserPageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserPageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  uid?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserPageListRelationFilter = {
  every?: Prisma.UserPageWhereInput
  some?: Prisma.UserPageWhereInput
  none?: Prisma.UserPageWhereInput
}

export type UserPageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserPageRankUidCompoundUniqueInput = {
  rank: string
  uid: string
}

export type UserPageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  uid?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  isPinned?: Prisma.SortOrder
}

export type UserPageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  uid?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  isPinned?: Prisma.SortOrder
}

export type UserPageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  uid?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  isPinned?: Prisma.SortOrder
}

export type UserPageCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserPageCreateWithoutUserInput, Prisma.UserPageUncheckedCreateWithoutUserInput> | Prisma.UserPageCreateWithoutUserInput[] | Prisma.UserPageUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPageCreateOrConnectWithoutUserInput | Prisma.UserPageCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserPageCreateManyUserInputEnvelope
  connect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
}

export type UserPageUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserPageCreateWithoutUserInput, Prisma.UserPageUncheckedCreateWithoutUserInput> | Prisma.UserPageCreateWithoutUserInput[] | Prisma.UserPageUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPageCreateOrConnectWithoutUserInput | Prisma.UserPageCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserPageCreateManyUserInputEnvelope
  connect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
}

export type UserPageUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserPageCreateWithoutUserInput, Prisma.UserPageUncheckedCreateWithoutUserInput> | Prisma.UserPageCreateWithoutUserInput[] | Prisma.UserPageUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPageCreateOrConnectWithoutUserInput | Prisma.UserPageCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserPageUpsertWithWhereUniqueWithoutUserInput | Prisma.UserPageUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserPageCreateManyUserInputEnvelope
  set?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  disconnect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  delete?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  connect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  update?: Prisma.UserPageUpdateWithWhereUniqueWithoutUserInput | Prisma.UserPageUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserPageUpdateManyWithWhereWithoutUserInput | Prisma.UserPageUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserPageScalarWhereInput | Prisma.UserPageScalarWhereInput[]
}

export type UserPageUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserPageCreateWithoutUserInput, Prisma.UserPageUncheckedCreateWithoutUserInput> | Prisma.UserPageCreateWithoutUserInput[] | Prisma.UserPageUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserPageCreateOrConnectWithoutUserInput | Prisma.UserPageCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserPageUpsertWithWhereUniqueWithoutUserInput | Prisma.UserPageUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserPageCreateManyUserInputEnvelope
  set?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  disconnect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  delete?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  connect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  update?: Prisma.UserPageUpdateWithWhereUniqueWithoutUserInput | Prisma.UserPageUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserPageUpdateManyWithWhereWithoutUserInput | Prisma.UserPageUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserPageScalarWhereInput | Prisma.UserPageScalarWhereInput[]
}

export type UserPageCreateNestedManyWithoutPageInput = {
  create?: Prisma.XOR<Prisma.UserPageCreateWithoutPageInput, Prisma.UserPageUncheckedCreateWithoutPageInput> | Prisma.UserPageCreateWithoutPageInput[] | Prisma.UserPageUncheckedCreateWithoutPageInput[]
  connectOrCreate?: Prisma.UserPageCreateOrConnectWithoutPageInput | Prisma.UserPageCreateOrConnectWithoutPageInput[]
  createMany?: Prisma.UserPageCreateManyPageInputEnvelope
  connect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
}

export type UserPageUncheckedCreateNestedManyWithoutPageInput = {
  create?: Prisma.XOR<Prisma.UserPageCreateWithoutPageInput, Prisma.UserPageUncheckedCreateWithoutPageInput> | Prisma.UserPageCreateWithoutPageInput[] | Prisma.UserPageUncheckedCreateWithoutPageInput[]
  connectOrCreate?: Prisma.UserPageCreateOrConnectWithoutPageInput | Prisma.UserPageCreateOrConnectWithoutPageInput[]
  createMany?: Prisma.UserPageCreateManyPageInputEnvelope
  connect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
}

export type UserPageUpdateManyWithoutPageNestedInput = {
  create?: Prisma.XOR<Prisma.UserPageCreateWithoutPageInput, Prisma.UserPageUncheckedCreateWithoutPageInput> | Prisma.UserPageCreateWithoutPageInput[] | Prisma.UserPageUncheckedCreateWithoutPageInput[]
  connectOrCreate?: Prisma.UserPageCreateOrConnectWithoutPageInput | Prisma.UserPageCreateOrConnectWithoutPageInput[]
  upsert?: Prisma.UserPageUpsertWithWhereUniqueWithoutPageInput | Prisma.UserPageUpsertWithWhereUniqueWithoutPageInput[]
  createMany?: Prisma.UserPageCreateManyPageInputEnvelope
  set?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  disconnect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  delete?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  connect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  update?: Prisma.UserPageUpdateWithWhereUniqueWithoutPageInput | Prisma.UserPageUpdateWithWhereUniqueWithoutPageInput[]
  updateMany?: Prisma.UserPageUpdateManyWithWhereWithoutPageInput | Prisma.UserPageUpdateManyWithWhereWithoutPageInput[]
  deleteMany?: Prisma.UserPageScalarWhereInput | Prisma.UserPageScalarWhereInput[]
}

export type UserPageUncheckedUpdateManyWithoutPageNestedInput = {
  create?: Prisma.XOR<Prisma.UserPageCreateWithoutPageInput, Prisma.UserPageUncheckedCreateWithoutPageInput> | Prisma.UserPageCreateWithoutPageInput[] | Prisma.UserPageUncheckedCreateWithoutPageInput[]
  connectOrCreate?: Prisma.UserPageCreateOrConnectWithoutPageInput | Prisma.UserPageCreateOrConnectWithoutPageInput[]
  upsert?: Prisma.UserPageUpsertWithWhereUniqueWithoutPageInput | Prisma.UserPageUpsertWithWhereUniqueWithoutPageInput[]
  createMany?: Prisma.UserPageCreateManyPageInputEnvelope
  set?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  disconnect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  delete?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  connect?: Prisma.UserPageWhereUniqueInput | Prisma.UserPageWhereUniqueInput[]
  update?: Prisma.UserPageUpdateWithWhereUniqueWithoutPageInput | Prisma.UserPageUpdateWithWhereUniqueWithoutPageInput[]
  updateMany?: Prisma.UserPageUpdateManyWithWhereWithoutPageInput | Prisma.UserPageUpdateManyWithWhereWithoutPageInput[]
  deleteMany?: Prisma.UserPageScalarWhereInput | Prisma.UserPageScalarWhereInput[]
}

export type UserPageCreateWithoutUserInput = {
  id?: string
  rank: string
  isPinned: boolean
  page: Prisma.PageCreateNestedOneWithoutUserPagesInput
}

export type UserPageUncheckedCreateWithoutUserInput = {
  id?: string
  pageId: string
  rank: string
  isPinned: boolean
}

export type UserPageCreateOrConnectWithoutUserInput = {
  where: Prisma.UserPageWhereUniqueInput
  create: Prisma.XOR<Prisma.UserPageCreateWithoutUserInput, Prisma.UserPageUncheckedCreateWithoutUserInput>
}

export type UserPageCreateManyUserInputEnvelope = {
  data: Prisma.UserPageCreateManyUserInput | Prisma.UserPageCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserPageUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserPageWhereUniqueInput
  update: Prisma.XOR<Prisma.UserPageUpdateWithoutUserInput, Prisma.UserPageUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserPageCreateWithoutUserInput, Prisma.UserPageUncheckedCreateWithoutUserInput>
}

export type UserPageUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserPageWhereUniqueInput
  data: Prisma.XOR<Prisma.UserPageUpdateWithoutUserInput, Prisma.UserPageUncheckedUpdateWithoutUserInput>
}

export type UserPageUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserPageScalarWhereInput
  data: Prisma.XOR<Prisma.UserPageUpdateManyMutationInput, Prisma.UserPageUncheckedUpdateManyWithoutUserInput>
}

export type UserPageScalarWhereInput = {
  AND?: Prisma.UserPageScalarWhereInput | Prisma.UserPageScalarWhereInput[]
  OR?: Prisma.UserPageScalarWhereInput[]
  NOT?: Prisma.UserPageScalarWhereInput | Prisma.UserPageScalarWhereInput[]
  id?: Prisma.UuidFilter<"UserPage"> | string
  pageId?: Prisma.UuidFilter<"UserPage"> | string
  uid?: Prisma.StringFilter<"UserPage"> | string
  rank?: Prisma.StringFilter<"UserPage"> | string
  isPinned?: Prisma.BoolFilter<"UserPage"> | boolean
}

export type UserPageCreateWithoutPageInput = {
  id?: string
  rank: string
  isPinned: boolean
  user: Prisma.UserCreateNestedOneWithoutUserPagesInput
}

export type UserPageUncheckedCreateWithoutPageInput = {
  id?: string
  uid: string
  rank: string
  isPinned: boolean
}

export type UserPageCreateOrConnectWithoutPageInput = {
  where: Prisma.UserPageWhereUniqueInput
  create: Prisma.XOR<Prisma.UserPageCreateWithoutPageInput, Prisma.UserPageUncheckedCreateWithoutPageInput>
}

export type UserPageCreateManyPageInputEnvelope = {
  data: Prisma.UserPageCreateManyPageInput | Prisma.UserPageCreateManyPageInput[]
  skipDuplicates?: boolean
}

export type UserPageUpsertWithWhereUniqueWithoutPageInput = {
  where: Prisma.UserPageWhereUniqueInput
  update: Prisma.XOR<Prisma.UserPageUpdateWithoutPageInput, Prisma.UserPageUncheckedUpdateWithoutPageInput>
  create: Prisma.XOR<Prisma.UserPageCreateWithoutPageInput, Prisma.UserPageUncheckedCreateWithoutPageInput>
}

export type UserPageUpdateWithWhereUniqueWithoutPageInput = {
  where: Prisma.UserPageWhereUniqueInput
  data: Prisma.XOR<Prisma.UserPageUpdateWithoutPageInput, Prisma.UserPageUncheckedUpdateWithoutPageInput>
}

export type UserPageUpdateManyWithWhereWithoutPageInput = {
  where: Prisma.UserPageScalarWhereInput
  data: Prisma.XOR<Prisma.UserPageUpdateManyMutationInput, Prisma.UserPageUncheckedUpdateManyWithoutPageInput>
}

export type UserPageCreateManyUserInput = {
  id?: string
  pageId: string
  rank: string
  isPinned: boolean
}

export type UserPageUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  page?: Prisma.PageUpdateOneRequiredWithoutUserPagesNestedInput
}

export type UserPageUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserPageUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserPageCreateManyPageInput = {
  id?: string
  uid: string
  rank: string
  isPinned: boolean
}

export type UserPageUpdateWithoutPageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
  user?: Prisma.UserUpdateOneRequiredWithoutUserPagesNestedInput
}

export type UserPageUncheckedUpdateWithoutPageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  uid?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserPageUncheckedUpdateManyWithoutPageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  uid?: Prisma.StringFieldUpdateOperationsInput | string
  rank?: Prisma.StringFieldUpdateOperationsInput | string
  isPinned?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type UserPageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pageId?: boolean
  uid?: boolean
  rank?: boolean
  isPinned?: boolean
  page?: boolean | Prisma.PageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userPage"]>

export type UserPageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pageId?: boolean
  uid?: boolean
  rank?: boolean
  isPinned?: boolean
  page?: boolean | Prisma.PageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userPage"]>

export type UserPageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pageId?: boolean
  uid?: boolean
  rank?: boolean
  isPinned?: boolean
  page?: boolean | Prisma.PageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userPage"]>

export type UserPageSelectScalar = {
  id?: boolean
  pageId?: boolean
  uid?: boolean
  rank?: boolean
  isPinned?: boolean
}

export type UserPageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pageId" | "uid" | "rank" | "isPinned", ExtArgs["result"]["userPage"]>
export type UserPageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  page?: boolean | Prisma.PageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserPageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  page?: boolean | Prisma.PageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserPageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  page?: boolean | Prisma.PageDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserPagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserPage"
  objects: {
    page: Prisma.$PagePayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pageId: string
    uid: string
    rank: string
    isPinned: boolean
  }, ExtArgs["result"]["userPage"]>
  composites: {}
}

export type UserPageGetPayload<S extends boolean | null | undefined | UserPageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPagePayload, S>

export type UserPageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserPageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserPageCountAggregateInputType | true
  }

export interface UserPageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserPage'], meta: { name: 'UserPage' } }
  /**
   * Find zero or one UserPage that matches the filter.
   * @param {UserPageFindUniqueArgs} args - Arguments to find a UserPage
   * @example
   * // Get one UserPage
   * const userPage = await prisma.userPage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserPageFindUniqueArgs>(args: Prisma.SelectSubset<T, UserPageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserPageClient<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserPage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserPageFindUniqueOrThrowArgs} args - Arguments to find a UserPage
   * @example
   * // Get one UserPage
   * const userPage = await prisma.userPage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserPageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserPageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserPageClient<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserPage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPageFindFirstArgs} args - Arguments to find a UserPage
   * @example
   * // Get one UserPage
   * const userPage = await prisma.userPage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserPageFindFirstArgs>(args?: Prisma.SelectSubset<T, UserPageFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserPageClient<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserPage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPageFindFirstOrThrowArgs} args - Arguments to find a UserPage
   * @example
   * // Get one UserPage
   * const userPage = await prisma.userPage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserPageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserPageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserPageClient<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserPages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserPages
   * const userPages = await prisma.userPage.findMany()
   * 
   * // Get first 10 UserPages
   * const userPages = await prisma.userPage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userPageWithIdOnly = await prisma.userPage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserPageFindManyArgs>(args?: Prisma.SelectSubset<T, UserPageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserPage.
   * @param {UserPageCreateArgs} args - Arguments to create a UserPage.
   * @example
   * // Create one UserPage
   * const UserPage = await prisma.userPage.create({
   *   data: {
   *     // ... data to create a UserPage
   *   }
   * })
   * 
   */
  create<T extends UserPageCreateArgs>(args: Prisma.SelectSubset<T, UserPageCreateArgs<ExtArgs>>): Prisma.Prisma__UserPageClient<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserPages.
   * @param {UserPageCreateManyArgs} args - Arguments to create many UserPages.
   * @example
   * // Create many UserPages
   * const userPage = await prisma.userPage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserPageCreateManyArgs>(args?: Prisma.SelectSubset<T, UserPageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserPages and returns the data saved in the database.
   * @param {UserPageCreateManyAndReturnArgs} args - Arguments to create many UserPages.
   * @example
   * // Create many UserPages
   * const userPage = await prisma.userPage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserPages and only return the `id`
   * const userPageWithIdOnly = await prisma.userPage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserPageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserPageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserPage.
   * @param {UserPageDeleteArgs} args - Arguments to delete one UserPage.
   * @example
   * // Delete one UserPage
   * const UserPage = await prisma.userPage.delete({
   *   where: {
   *     // ... filter to delete one UserPage
   *   }
   * })
   * 
   */
  delete<T extends UserPageDeleteArgs>(args: Prisma.SelectSubset<T, UserPageDeleteArgs<ExtArgs>>): Prisma.Prisma__UserPageClient<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserPage.
   * @param {UserPageUpdateArgs} args - Arguments to update one UserPage.
   * @example
   * // Update one UserPage
   * const userPage = await prisma.userPage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserPageUpdateArgs>(args: Prisma.SelectSubset<T, UserPageUpdateArgs<ExtArgs>>): Prisma.Prisma__UserPageClient<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserPages.
   * @param {UserPageDeleteManyArgs} args - Arguments to filter UserPages to delete.
   * @example
   * // Delete a few UserPages
   * const { count } = await prisma.userPage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserPageDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserPageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserPages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserPages
   * const userPage = await prisma.userPage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserPageUpdateManyArgs>(args: Prisma.SelectSubset<T, UserPageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserPages and returns the data updated in the database.
   * @param {UserPageUpdateManyAndReturnArgs} args - Arguments to update many UserPages.
   * @example
   * // Update many UserPages
   * const userPage = await prisma.userPage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserPages and only return the `id`
   * const userPageWithIdOnly = await prisma.userPage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserPageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserPageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserPage.
   * @param {UserPageUpsertArgs} args - Arguments to update or create a UserPage.
   * @example
   * // Update or create a UserPage
   * const userPage = await prisma.userPage.upsert({
   *   create: {
   *     // ... data to create a UserPage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserPage we want to update
   *   }
   * })
   */
  upsert<T extends UserPageUpsertArgs>(args: Prisma.SelectSubset<T, UserPageUpsertArgs<ExtArgs>>): Prisma.Prisma__UserPageClient<runtime.Types.Result.GetResult<Prisma.$UserPagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserPages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPageCountArgs} args - Arguments to filter UserPages to count.
   * @example
   * // Count the number of UserPages
   * const count = await prisma.userPage.count({
   *   where: {
   *     // ... the filter for the UserPages we want to count
   *   }
   * })
  **/
  count<T extends UserPageCountArgs>(
    args?: Prisma.Subset<T, UserPageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserPageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserPage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserPageAggregateArgs>(args: Prisma.Subset<T, UserPageAggregateArgs>): Prisma.PrismaPromise<GetUserPageAggregateType<T>>

  /**
   * Group by UserPage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserPageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserPageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserPageGroupByArgs['orderBy'] }
      : { orderBy?: UserPageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserPageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserPageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserPage model
 */
readonly fields: UserPageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserPage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserPageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  page<T extends Prisma.PageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PageDefaultArgs<ExtArgs>>): Prisma.Prisma__PageClient<runtime.Types.Result.GetResult<Prisma.$PagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserPage model
 */
export interface UserPageFieldRefs {
  readonly id: Prisma.FieldRef<"UserPage", 'String'>
  readonly pageId: Prisma.FieldRef<"UserPage", 'String'>
  readonly uid: Prisma.FieldRef<"UserPage", 'String'>
  readonly rank: Prisma.FieldRef<"UserPage", 'String'>
  readonly isPinned: Prisma.FieldRef<"UserPage", 'Boolean'>
}
    

// Custom InputTypes
/**
 * UserPage findUnique
 */
export type UserPageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
  /**
   * Filter, which UserPage to fetch.
   */
  where: Prisma.UserPageWhereUniqueInput
}

/**
 * UserPage findUniqueOrThrow
 */
export type UserPageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
  /**
   * Filter, which UserPage to fetch.
   */
  where: Prisma.UserPageWhereUniqueInput
}

/**
 * UserPage findFirst
 */
export type UserPageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
  /**
   * Filter, which UserPage to fetch.
   */
  where?: Prisma.UserPageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPages to fetch.
   */
  orderBy?: Prisma.UserPageOrderByWithRelationInput | Prisma.UserPageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserPages.
   */
  cursor?: Prisma.UserPageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserPages.
   */
  distinct?: Prisma.UserPageScalarFieldEnum | Prisma.UserPageScalarFieldEnum[]
}

/**
 * UserPage findFirstOrThrow
 */
export type UserPageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
  /**
   * Filter, which UserPage to fetch.
   */
  where?: Prisma.UserPageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPages to fetch.
   */
  orderBy?: Prisma.UserPageOrderByWithRelationInput | Prisma.UserPageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserPages.
   */
  cursor?: Prisma.UserPageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserPages.
   */
  distinct?: Prisma.UserPageScalarFieldEnum | Prisma.UserPageScalarFieldEnum[]
}

/**
 * UserPage findMany
 */
export type UserPageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
  /**
   * Filter, which UserPages to fetch.
   */
  where?: Prisma.UserPageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserPages to fetch.
   */
  orderBy?: Prisma.UserPageOrderByWithRelationInput | Prisma.UserPageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserPages.
   */
  cursor?: Prisma.UserPageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserPages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserPages.
   */
  skip?: number
  distinct?: Prisma.UserPageScalarFieldEnum | Prisma.UserPageScalarFieldEnum[]
}

/**
 * UserPage create
 */
export type UserPageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
  /**
   * The data needed to create a UserPage.
   */
  data: Prisma.XOR<Prisma.UserPageCreateInput, Prisma.UserPageUncheckedCreateInput>
}

/**
 * UserPage createMany
 */
export type UserPageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserPages.
   */
  data: Prisma.UserPageCreateManyInput | Prisma.UserPageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserPage createManyAndReturn
 */
export type UserPageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * The data used to create many UserPages.
   */
  data: Prisma.UserPageCreateManyInput | Prisma.UserPageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserPage update
 */
export type UserPageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
  /**
   * The data needed to update a UserPage.
   */
  data: Prisma.XOR<Prisma.UserPageUpdateInput, Prisma.UserPageUncheckedUpdateInput>
  /**
   * Choose, which UserPage to update.
   */
  where: Prisma.UserPageWhereUniqueInput
}

/**
 * UserPage updateMany
 */
export type UserPageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserPages.
   */
  data: Prisma.XOR<Prisma.UserPageUpdateManyMutationInput, Prisma.UserPageUncheckedUpdateManyInput>
  /**
   * Filter which UserPages to update
   */
  where?: Prisma.UserPageWhereInput
  /**
   * Limit how many UserPages to update.
   */
  limit?: number
}

/**
 * UserPage updateManyAndReturn
 */
export type UserPageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * The data used to update UserPages.
   */
  data: Prisma.XOR<Prisma.UserPageUpdateManyMutationInput, Prisma.UserPageUncheckedUpdateManyInput>
  /**
   * Filter which UserPages to update
   */
  where?: Prisma.UserPageWhereInput
  /**
   * Limit how many UserPages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserPage upsert
 */
export type UserPageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
  /**
   * The filter to search for the UserPage to update in case it exists.
   */
  where: Prisma.UserPageWhereUniqueInput
  /**
   * In case the UserPage found by the `where` argument doesn't exist, create a new UserPage with this data.
   */
  create: Prisma.XOR<Prisma.UserPageCreateInput, Prisma.UserPageUncheckedCreateInput>
  /**
   * In case the UserPage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserPageUpdateInput, Prisma.UserPageUncheckedUpdateInput>
}

/**
 * UserPage delete
 */
export type UserPageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
  /**
   * Filter which UserPage to delete.
   */
  where: Prisma.UserPageWhereUniqueInput
}

/**
 * UserPage deleteMany
 */
export type UserPageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserPages to delete
   */
  where?: Prisma.UserPageWhereInput
  /**
   * Limit how many UserPages to delete.
   */
  limit?: number
}

/**
 * UserPage without action
 */
export type UserPageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserPage
   */
  select?: Prisma.UserPageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserPage
   */
  omit?: Prisma.UserPageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserPageInclude<ExtArgs> | null
}
