-- ALTER TABLE "Page"
-- ADD COLUMN     "description" TEXT NOT NULL DEFAULT '';


-- -- AlterTable
-- ALTER TABLE "Page" ALTER COLUMN "description" DROP DEFAULT,

ALTER TABLE "Page" DROP COLUMN "name",
ADD COLUMN     "title" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Page" ALTER COLUMN "title" DROP DEFAULT;
