import type { Context, EntityId } from "@woven-ecs/core";
import type { Vec2 } from "@infinitecanvas/math";

import type { PointerButton, PointerType } from "../components/Pointer";

/**
 * Pointer input event types generated by getPointerInput.
 *
 * - `pointerDown` - Pointer was pressed (mouse click, touch start, pen down)
 * - `pointerMove` - Pointer moved while pressed, or modifier keys changed
 * - `pointerUp` - Pointer was released
 * - `click` - Pointer was released without significant movement (quick tap)
 * - `cancel` - Action was cancelled (escape pressed, multi-touch detected)
 * - `frame` - Continuous event fired every frame while pointer is active
 */
export type PointerInputType =
  | "pointerDown"
  | "pointerMove"
  | "pointerUp"
  | "click"
  | "cancel"
  | "frame";

/**
 * A high-level pointer input event for state machine consumption.
 *
 * Generated by `getPointerInput()` from raw ECS pointer data.
 * Includes position, velocity, modifier key state, and optional camera info.
 */
export interface PointerInput {
  /** Event type, used as the XState event discriminator */
  type: PointerInputType;
  /** ECS context for accessing components in state machine actions */
  ctx: Context;
  /** Position in screen/client coordinates [x, y] */
  screenPosition: Vec2;
  /** Position in world coordinates [x, y] (requires Camera singleton) */
  worldPosition: Vec2;
  /** Velocity in screen pixels per second [vx, vy] */
  velocity: Vec2;
  /** Pressure from 0 to 1 (for pen/touch, 0.5 for mouse) */
  pressure: number;
  /** Which button is pressed */
  button: PointerButton;
  /** Type of pointer device */
  pointerType: PointerType;
  /** Whether the pointer target was obscured (not the editor element) */
  obscured: boolean;
  /** Whether Shift key is held */
  shiftDown: boolean;
  /** Whether Alt/Option key is held */
  altDown: boolean;
  /** Whether Ctrl (Windows/Linux) or Cmd (Mac) key is held */
  modDown: boolean;
  /** Camera left position when event was generated */
  cameraLeft: number;
  /** Camera top position when event was generated */
  cameraTop: number;
  /** Camera zoom level when event was generated */
  cameraZoom: number;
  /** Entity ID of the pointer (for tracking across events) */
  pointerId: number;
  /** Entity IDs at the pointer position, sorted by z-order (topmost first) */
  intersects: EntityId[];
}

/**
 * Mouse input event types generated by getMouseInput.
 */
export type MouseInputType = "wheel" | "mouseMove";

/**
 * A high-level mouse input event for state machine consumption.
 *
 * Generated by `getMouseInput()` from raw ECS mouse data.
 * Separate from pointer input - covers wheel and hover movement.
 */
export interface MouseInput {
  /** Event type */
  type: MouseInputType;
  /** ECS context for accessing components in state machine actions */
  ctx: Context;
  /** Position in screen/client coordinates [x, y] */
  screenPosition: Vec2;
  /** Position in world coordinates [x, y] (requires Camera singleton) */
  worldPosition: Vec2;
  /** Horizontal wheel delta (positive = scroll right) */
  wheelDeltaX: number;
  /** Vertical wheel delta (positive = scroll down) */
  wheelDeltaY: number;
}

/**
 * A high-level frame input event for state machine consumption.
 *
 * Generated by `getFrameInput()` for driving animations and
 * time-based state machine transitions.
 */
export interface FrameInput {
  /** Event type, always "frame" */
  type: "frame";
  /** ECS context for accessing components in state machine actions */
  ctx: Context;
  /** Time since last frame in seconds */
  delta: number;
  /** Current frame number */
  frameNumber: number;
  /** Timestamp of current frame in milliseconds (from performance.now()) */
  time: number;
}

/**
 * Keyboard input event types generated by getKeyboardInput.
 */
export type KeyboardInputType = "keyDown" | "keyUp";

/**
 * A high-level keyboard input event for state machine consumption.
 *
 * Generated by `getKeyboardInput()` from raw ECS keyboard data.
 * Use with specific keys you want to track (e.g., Escape for cancel).
 */
export interface KeyboardInput {
  /** Event type */
  type: KeyboardInputType;
  /** The key that was pressed or released (use Key.* constants) */
  key: number;
  /** ECS context for accessing components in state machine actions */
  ctx: Context;
}

/**
 * Options for getPointerInput.
 */
export interface PointerInputOptions {
  /**
   * Include a 'frame' event every tick while a pointer is active.
   * Useful for continuous actions like edge scrolling.
   * @default false
   */
  includeFrameEvent?: boolean;

  /**
   * Distance threshold for click detection (in pixels).
   * If pointer moves less than this distance, a 'click' event is generated on release.
   * @default 3
   */
  clickMoveThreshold?: number;

  /**
   * Frame threshold for click detection.
   * If pointer is held for more frames than this, no 'click' event is generated.
   * @default 30
   */
  clickFrameThreshold?: number;
}
